services:

  filebrowser:
    image: hurlenko/filebrowser:latest
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Costa_Rica
      - FB_BASEURL=/filebrowser
    ports:
      - "8250:8080"
    volumes:
      - ./fb-data:/data
      - ./fb-config:/config
      - ./music:/data/music
      - ./movies:/data/movies
      - ./photos:/data/photos
    restart: unless-stopped
